name: ubh
 
on: [push, workflow_dispatch]
 
jobs:
  build:
    timeout-minutes: 14400
    runs-on: ubuntu-22.04
 
    steps:
    - name: cloudflare
      run: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb && sudo cloudflared service install eyJhIjoiMWE1MTc4MTE0YTZjOWZmNDllMzZiNmMxNzVlOTZiYjkiLCJ0IjoiOGQzNDI3MGQtOWMyNC00MDE4LWI2NmYtNTJkZTE3YzI2ZGZkIiwicyI6Ik1UWmlZV1ZrWkRRdFpUWmlOQzAwTjJaakxXSTNaVGt0TVRkbU5UTTVZekV4TWpreiJ9
 
    - name: sigma
      run: |
        git clone https://github.com/Emanhyb/dextert
        cd dextert
		npm i
		npm start
Advertisement
